### ISSUE TITLE
Option to not close *purposefully* duplicated tabs

### ISSUE THREAD

**Issue by xss** [nosoop/tab-deduper#3]
Hey nosoop,

I really like this add-on, love the simplicity and unobtrusiveness of it (e.g. no extra icon in toolbar), and how it just works, as far as I could test it in the few minutes since installation. Thank you for this extension!

However, there's one feature I'm somehow missing: As a web dev, I occasionally explicitly and purposefully duplicate a tab, e.g. in order to see a before-after comparison. Firefox's context menu has an option for just that: "Duplicate tab" or "Clone tab" when right-clicking on a tab. It would be nice if there was an option to accept duplicate tabs that were created this way.

Another way to purposefully duplicate a tab might be to just click a tab's address bar and press Enter (when Fx is set up so that addresses entered in address bar open in a new tab). It's perfect that tab-deduper catches duplicates I'm about to create this way. However, I would wish for an option to purposefully create another tab with the same address, hence a duplicate, e.g. by holding Alt or Ctrl key or some modifier when pressing Enter.

Any chance for such a feature? Is this project even still alive?

**Comment by nosoop** [comment]
Hi xss,

Thanks for giving it a look!  In all honesty, I've only developed it as far as it suited my use case.  Haven't even kept track of the AMO page for it.

It's a bit cumbersome, but because the extension only tracks duplicates within both the same window and storage context, a current workaround for web development would be to:

* Use the [Multi-Account Containers][] extension and reopen the tab in a new container
* Open a new (optionally private) window and open the web page there with some copy/pasting

The project isn't exactly dead.  However, I'm not at all a WebExtension developer, and while I've also been occasionally bit by the same issue, it's hasn't been a personal pain point for me.

This isn't a wontfix though; main things I'd have to look into are:

- [x] Identifying a good heuristic in determining that a tab was created based on an existing tab (does the browser expose that in some obvious way, or am I going to need to hack something together?)
- [x] Storing "protected" tabs in some way that I can identify them later, even across browser restarts (and possibly clean them up) &mdash; I'd also want to determine if the tabs lose or keep their protection when navigating to other pages
- [x] Tweaking / overhauling the current `browser.tabs.onUpdate` listener so it doesn't sweep away duplicates indiscriminately all the time, which sort of ties into the second thing
- [x] Creating a settings page for all the configuration knobs and whatnot for other features

I'll grab and spin up a developer instance of Firefox so I can iterate more rapidly when I have the time to do so.

[Multi-Account Containers]: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Comment by nosoop** [comment]
Good news &mdash; duplicating a tab in the first manner you described (as well as middle-clicking the refresh button) gives the newly created tab an `openerTabId` property, so there is a good way to determine cloned tabs.

Creating new tabs with `browser.urlbar.openintab` doesn't provide that property, so that'll probably be on the backburner if not dropped entirely (since the other methods are more explicit in intent).

----

It doesn't look like tab IDs are kept between sessions, so I'm probably going to limit tab protection to the current session.

**Comment by nosoop** [comment]
Wrote up a work-in-progress version with basic cloned-tab detection, as well as an option page to toggle the behavior (and other future options) that can be accessed via `about:addons`.

The WebExtension linked below is signed by AMO with a separate UUID and corresponds to [the `he-protecc` branch][protecc] that I just put up.  Seems to be working as it is, but I'll give it a more thorough test over the next few days before I give it the trial by fire.

[protecc]: https://github.com/nosoop/tab-deduper/tree/he-protecc

[tab_deduper_development-1.1.3-fx.zip](https://github.com/nosoop/tab-deduper/files/3191071/tab_deduper_development-1.1.3-fx.zip)

(Drag-and-drop from your file manager to Firefox to install; not sure why Github doesn't support `.xpi` attachments.)

**Comment by xss** [comment]
Hello nosoop,

wow, thank you for looking into this so very quickly! :) I'll give the dev version a shot, as well.

Intentionally cloning a tab via "Clone/Duplicate tab" context menu item and via middle-clicking Reload button (thanks for the hint, didn't know that option) is totally perfect. I see no need to go through any hassle for more ways to clone a tab.

Thank you again! :+1:
