### ISSUE TITLE
refresh original tab when attempting to open a duplicate

### ISSUE THREAD

**Issue by aecepoglu** [nosoop/tab-deduper#4]
I use this plugin in my development workflow like so:

1. My development webserver (which serves the file `my-file.html`) is running at localhost:8080, and I have one tab open in Firefox for that URL
2. I make some edits to `my-file.html` and re-open the URL
3. Thanks to tab-deduper, The original tab for `my-file.html` is opened
4. I refresh the tab to see my changes

I would love it if there was an option to refresh the page automatically.

**Comment by nosoop** [comment]
I'd say that <kbd>F5</kbd> is fine enough, but to each their own.

That said, since I've added a basic settings system in the development version, I wouldn't mind adding this feature in at the same time I add alternate "tab priority" options (e.g., instead of always keeping the oldest tab, you can opt to keep the newest).

Will probably add it as a separate option that is off by default.

**Comment by aecepoglu** [comment]
<kbd>f5</kbd> is fine, but of course I was looking for a way to shave an extra keystroke from my pipeline :)

The mentioned option would also solve the problem
